from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ground = QtWidgets.QLineEdit(parent=self.tab)
        self.ground.setObjectName("ground")
        self.gridLayout_2.addWidget(self.ground, 2, 2, 1, 2)
        self.volume = QtWidgets.QLineEdit(parent=self.tab)
        self.volume.setObjectName("volume")
        self.gridLayout_2.addWidget(self.volume, 5, 3, 1, 1)
        self.sort_name = QtWidgets.QLineEdit(parent=self.tab)
        self.sort_name.setObjectName("sort_name")
        self.gridLayout_2.addWidget(self.sort_name, 0, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.price = QtWidgets.QLineEdit(parent=self.tab)
        self.price.setObjectName("price")
        self.gridLayout_2.addWidget(self.price, 4, 1, 1, 3)
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(parent=self.tab)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 6, 2, 1, 2)
        self.description = QtWidgets.QLineEdit(parent=self.tab)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 3, 2, 1, 2)
        self.degree_roating = QtWidgets.QLineEdit(parent=self.tab)
        self.degree_roating.setObjectName("degree_roating")
        self.gridLayout_2.addWidget(self.degree_roating, 1, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_71 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 5, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 6, 0, 1, 3)
        self.volume1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.volume1.setObjectName("volume1")
        self.gridLayout_3.addWidget(self.volume1, 6, 3, 1, 1)
        self.ground1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.ground1.setObjectName("ground1")
        self.gridLayout_3.addWidget(self.ground1, 2, 2, 1, 2)
        self.sort_name1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.sort_name1.setObjectName("sort_name1")
        self.gridLayout_3.addWidget(self.sort_name1, 0, 1, 1, 3)
        self.label_31 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 2)
        self.description1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.description1.setObjectName("description1")
        self.gridLayout_3.addWidget(self.description1, 3, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.taste = QtWidgets.QLineEdit(parent=self.tab_2)
        self.taste.setObjectName("taste")
        self.gridLayout_3.addWidget(self.taste, 4, 3, 1, 1)
        self.degree_roating1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.degree_roating1.setObjectName("degree_roating1")
        self.gridLayout_3.addWidget(self.degree_roating1, 1, 1, 1, 3)
        self.price1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.price1.setObjectName("price1")
        self.gridLayout_3.addWidget(self.price1, 5, 1, 1, 3)
        self.label_21 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 3, 0, 1, 1)
        self.label1 = QtWidgets.QLabel(parent=self.tab_2)
        self.label1.setObjectName("label1")
        self.gridLayout_3.addWidget(self.label1, 0, 0, 1, 1)
        self.save_btn1 = QtWidgets.QPushButton(parent=self.tab_2)
        self.save_btn1.setObjectName("save_btn1")
        self.gridLayout_3.addWidget(self.save_btn1, 7, 2, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Молотый/В Зренах"))
        self.label_5.setText(_translate("Dialog", "Объем упаковки"))
        self.label_4.setText(_translate("Dialog", "Описание"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_2.setText(_translate("Dialog", "Степень Обжарки"))
        self.save_btn.setText(_translate("Dialog", "Сохранить изменения"))
        self.label_7.setText(_translate("Dialog", "Цена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.label_71.setText(_translate("Dialog", "Цена"))
        self.label_51.setText(_translate("Dialog", "Объем упаковки"))
        self.label_31.setText(_translate("Dialog", "Молотый/В Зренах"))
        self.label_6.setText(_translate("Dialog", "Вкус"))
        self.label_21.setText(_translate("Dialog", "Степень Обжарки"))
        self.label_41.setText(_translate("Dialog", "Описание"))
        self.label1.setText(_translate("Dialog", "Название сорта"))
        self.save_btn1.setText(_translate("Dialog", "Обновить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))